### ISSUE TITLE
Error when generate fuse data

### ISSUE THREAD

**Issue by WilliamKRobert** [zju3dv/pvnet-rendering#11]
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 20, in run_fuse
    run()
  File "~/pvnet-rendering/fuse/fuse.py", line 336, in run
    prepare_dataset_parallel(output_dir, linemod_dir, linemod_orig_dir, fuse_num, background_dir, cache_dir, worker_num)
  File "~/pvnet-rendering/fuse/fuse.py", line 217, in prepare_dataset_parallel
    f.result()
  File "~/packages/miniconda2/envs/blender/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "~/packages/miniconda2/envs/blender/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (96,44) (96,44,1) (96,44)

**Comment by pengsida** [comment]
I cannot see the concrete line that produces the error.
