### ISSUE TITLE
Dear author, Can you help me solve this problem? ModuleNotFoundError: No module named 'OpenEXR'

### ISSUE THREAD

**Issue by deerlululu** [zju3dv/pvnet-rendering#14]
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 11, in run_rendering
    from blender.render_utils import Renderer, YCBRenderer
  File "/home/net663/pvnet-rendering-master/blender/render_utils.py", line 9, in <module>
    import OpenEXR
ModuleNotFoundError: No module named 'OpenEXR'

**Comment by deerlululu** [comment]
I tried to download the library, but it didn't work

**Comment by pengsida** [comment]
Could you provide more detail?

**Comment by deerlululu** [comment]
Problem after executing this code:python run.py --type rendering

**Comment by pengsida** [comment]
You could google how to install a python library.

**Comment by deerlululu** [comment]
Thank you

**Comment by ming-c** [comment]
Solved with `(sudo) pip install openexr`

**Comment by monajalal** [comment]
@pengsida 

```

root@fae597dbdb79:/home/pvnet-rendering# /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/pip3 install openexr
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting openexr
  Using cached OpenEXR-1.3.9.tar.gz (13 kB)
Building wheels for collected packages: openexr
  Building wheel for openexr (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/python3.5m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ge947tkt
       cwd: /tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/
  Complete output (17 lines):
  Looking for libOpenEXR...
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying Imath.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building 'OpenEXR' extension
  creating build/temp.linux-x86_64-3.5
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/OpenEXR -I/usr/include/Imath -I/usr/local/include/Imath -I/opt/local/include/Imath -I/home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m -c OpenEXR.cpp -o build/temp.linux-x86_64-3.5/OpenEXR.o -g -DVERSION="1.3.9"
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  OpenEXR.cpp:1:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for openexr
  Running setup.py clean for openexr
Failed to build openexr
Installing collected packages: openexr
    Running setup.py install for openexr ... error
    ERROR: Command errored out with exit status 1:
     command: /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/python3.5m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9kh4tor5/install-record.txt --single-version-externally-managed --compile --install-headers /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m/openexr
         cwd: /tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/
    Complete output (17 lines):
    Looking for libOpenEXR...
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying Imath.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building 'OpenEXR' extension
    creating build/temp.linux-x86_64-3.5
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/OpenEXR -I/usr/include/Imath -I/usr/local/include/Imath -I/opt/local/include/Imath -I/home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m -c OpenEXR.cpp -o build/temp.linux-x86_64-3.5/OpenEXR.o -g -DVERSION="1.3.9"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    OpenEXR.cpp:1:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/python3.5m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1uijbjl8/openexr_abb1a397c258434a975bc51ccdb88faa/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9kh4tor5/install-record.txt --single-version-externally-managed --compile --install-headers /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m/openexr Check the logs for full command output.

```
