### ISSUE TITLE
About importerror: No module named 'transforms3d'

### ISSUE THREAD

**Issue by emojiLee** [zju3dv/pvnet-rendering#23]
Hi, pengsida
thank you for sharing the code！
I followed the guide of pvnet was completed demo and test,  the step of train have some errors: no '.pkl' file of render and fuse, so i downloaded the datasets of LINEMOD,LINEMOD_ORIG and SUN，when runing the command  "python run.py --type rendering",  error:  ‘ImportError: No module named 'transforms3d'’. but i installed transforms3d in requirements.txt （transforms3d version is 0.3.1），then i uninstall and reinstall in python environment，no well. 

I will be looking forward to your reply.

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet-rendering/issues/3

**Comment by emojiLee** [comment]
thanks~It's ok. 
But I used the blender2.79a, error:  no found cuda. PS:My Nvidia Driver is latest version '435'
so I used the blender2.8 that found cpu and gpu. 
When runing "python run.py --type rendering", Error: many objects no attribute 'xxxxxx'. Blender2.8 haven some changes , then i found the Blender 2.8.0 Python API, I don't know how to replace...use blender for the first time.

Example（render_backend.py）:
---->  bpy.context.user_preferences.addons['cycles'].preferences.compute_device_type = "CUDA"
AttributeError: 'Context' object has no attribute 'user_preferences'

----->diffuse_node = material.node_tree.nodes['Diffuse BSDF']
KeyError: 'bpy_prop_collection[key]: key "Diffuse BSDF" not found'

**Comment by pengsida** [comment]
Use blender 2.79a.
If blender did not find cuda, you need to check your `PATH` or try to downgrade the nvidia driver.

**Comment by emojiLee** [comment]
Thanks for you,
I had tried to upgrade the latest version of nvidia driver  before used blender2.8.(GeRorce GTX 1660 Ti, nvidia driver :435.21).
Added cuda,cuda-10.1 path in the '.bashrc'.
Added blender path in the 'config.py'.
Still,
TypeError: bpy_struct: item.attr = val: enum "CUDA" not found in ('NONE').
I have no ideas.

**Comment by pengsida** [comment]
Please list detailed error message.

**Comment by emojiLee** [comment]
$ python run.py --type rendering

Read prefs: /home/lina/.config/blender/2.79/config/userpref.blend
found bundled python: /home/lina/download/blender-2.79a-linux-glibc219-x86_64/2.79/python
Read blend: /home/lina/code_download/pvnet-rendering-master/data/blank.blend

Successfully imported '/home/lina/code_download/pvnet-rendering-master/data/LINEMOD/cat/cat.ply' in 1.093 sec
Traceback (most recent call last):
  File "/home/lina/code_download/pvnet-rendering-master/blender/render_backend.py", line 473, in <module>
    batch_render_with_linemod(args, camera)
  File "/home/lina/code_download/pvnet-rendering-master/blender/render_backend.py", line 352, in batch_render_with_linemod
    bpy.context.user_preferences.addons['cycles'].preferences.compute_device_type = "CUDA"
TypeError: bpy_struct: item.attr = val: enum "CUDA" not found in ('NONE')

Blender quit

**Comment by pengsida** [comment]
Could you `echo $PATH` and `echo $LD_LIBRARY_PATH`.

**Comment by emojiLee** [comment]
(python36) lina@lina-MS-7C39:~$ echo $PATH
/usr/local/cuda-10.1/bin:/home/lina/.conda/envs/python36/bin:/home/lina/anaconda3/bin:/home/lina/anaconda3/condabin:/home/lina/bin:/home/lina/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

(python36) lina@lina-MS-7C39:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda-10.1/lib64:/home/lina/code_download/pvnet-master/lib/utils/extend_utils/lib:/opt/OpenBLAS/lib

**Comment by pengsida** [comment]
Your environment is correct.
It is because blender 2.79 does not support cuda 10.
You could try cuda 9.0.

**Comment by sherwoac** [comment]
You might find my conda environment definition useful, everything seems to execute for me. see attached.
[environment.zip](https://github.com/zju3dv/pvnet-rendering/files/3756617/environment.zip)

**Comment by emojiLee** [comment]
wow, thanks~
I'll try.

**Comment by emojiLee** [comment]
Hi, pengsida. I got the results for 'rendering' and 'fuse'.
Why there are only 9 pictures in rendering results?

**Comment by pengsida** [comment]
https://github.com/zju3dv/pvnet-rendering/blob/master/config.py#L42

**Comment by emojiLee** [comment]
thanks~

**Comment by tensarflow** [comment]
> Hi, pengsida. I got the results for 'rendering' and 'fuse'. Why there are only 9 pictures in rendering results?

How did you solve your problem?

I have a similar issue. I'm using an RTX3090 which does only support CUDA 11.1 and up. Unfortunately blender needs CUDA 8:
Console error:
```
CUDA version 12.10 detected, build may succeed but only CUDA 8.0 is officially supported.
```

of course it throws tons of errors while compiling the CUDA kernels:
(I'm using CPU as of now but its super slow)
```

CUDA version 12.10 detected, build may succeed but only CUDA 8.0 is officially supported.
Compiling CUDA kernel ...
"/usr/local/cuda/bin/nvcc" -arch=sm_86 --cubin "/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernels/cuda/kernel.cu" -o "/home/daimia/.cache/cycles/kernels/cycles_kernel_sm86_666D40D8FFAB401D47DC3343B4B28AFA.cubin" -m64 --ptxas-options="-v" --use_fast_math -DNVCC -D__KERNEL_CUDA_VERSION__=122 -I"/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source" 
/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/util/util_math_float3.h(315): error: identifier "saturate" is undefined
   return make_float3(saturate(a.x), saturate(a.y), saturate(a.z));
                      ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(120): error: texture is not a template
  typedef texture<float4, 1> texture_float4;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(121): error: texture is not a template
  typedef texture<float2, 1> texture_float2;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(122): error: texture is not a template
  typedef texture<float, 1> texture_float;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(123): error: texture is not a template
  typedef texture<uint, 1> texture_uint;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(124): error: texture is not a template
  typedef texture<int, 1> texture_int;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(125): error: texture is not a template
  typedef texture<uint4, 1> texture_uint4;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(126): error: texture is not a template
  typedef texture<uchar, 1> texture_uchar;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(127): error: texture is not a template
  typedef texture<uchar4, 1> texture_uchar4;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(128): error: texture is not a template
  typedef texture<float4, 2> texture_image_float4;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(129): error: texture is not a template
  typedef texture<float4, 3> texture_image3d_float4;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_compat_cuda.h(130): error: texture is not a template
  typedef texture<uchar4, 2, cudaReadModeNormalizedFloat> texture_image_uchar4;
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_globals.h(131): error: identifier "saturate" is undefined
   x = saturate(x)*(size-1);
       ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_globals.h(147): error: identifier "saturate" is undefined
   y = saturate(y)*(ysize-1);
       ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_film.h(30): error: identifier "saturate" is undefined
   result.w = saturate(result.w);
              ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_film.h(40): error: identifier "saturate" is undefined
   result.x = (uchar)(saturate(color.x)*255.0f);
                      ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/geom/geom_curve.h(535): error: identifier "saturate" is undefined
      w = saturate(w);
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/geom/geom_curve.h(653): error: identifier "saturate" is undefined
      w = saturate(w);
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_oren_nayar.h(49): error: identifier "saturate" is undefined
   sigma = saturate(sigma);
           ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(283): error: identifier "saturate" is undefined
   bsdf->alpha_x = saturate(bsdf->alpha_x);
                   ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(293): error: identifier "saturate" is undefined
   bsdf->extra->cspec0.x = saturate(bsdf->extra->cspec0.x);
                           ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(311): error: identifier "saturate" is undefined
   bsdf->extra->cspec0.x = saturate(bsdf->extra->cspec0.x);
                           ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(346): error: identifier "saturate" is undefined
   bsdf->alpha_x = saturate(bsdf->alpha_x);
                   ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(356): error: identifier "saturate" is undefined
   bsdf->extra->cspec0.x = saturate(bsdf->extra->cspec0.x);
                           ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(376): error: identifier "saturate" is undefined
   bsdf->alpha_x = saturate(bsdf->alpha_x);
                   ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(765): error: identifier "saturate" is undefined
   bsdf->alpha_x = saturate(bsdf->alpha_x);
                   ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(774): error: identifier "saturate" is undefined
   bsdf->alpha_x = saturate(bsdf->alpha_x);
                   ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet.h(783): error: identifier "saturate" is undefined
   bsdf->alpha_x = saturate(bsdf->alpha_x);
                   ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(193): error: identifier "saturate" is undefined
   return 2.0f * saturate(h) - 1.0f;
                 ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(198): error: identifier "saturate" is undefined
   return saturate(0.5f * (h + 1.0f));
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(245): error: identifier "saturate" is undefined
   return saturate(albedo);
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(253): error: identifier "saturate" is undefined
   a = saturate(a);
       ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(343): error: identifier "saturate" is undefined
   bsdf->extra->color.x = saturate(bsdf->extra->color.x);
                          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(492): error: identifier "saturate" is undefined
   bsdf->extra->color.x = saturate(bsdf->extra->color.x);
                          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_microfacet_multi.h(506): error: identifier "saturate" is undefined
   bsdf->extra->color.x = saturate(bsdf->extra->color.x);
                          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_toon.h(50): error: identifier "saturate" is undefined
   bsdf->size = saturate(bsdf->size);
                ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bsdf_toon.h(142): error: identifier "saturate" is undefined
   bsdf->size = saturate(bsdf->size);
                ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bssrdf.h(165): error: identifier "saturate" is undefined
    x = saturate(x - f/f_);
        ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/closure/bssrdf.h(393): error: identifier "saturate" is undefined
    bssrdf->texture_blur = saturate(bssrdf->texture_blur);
                           ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_color_util.h(257): error: identifier "saturate" is undefined
   outcol.x = saturate(col.x);
              ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_color_util.h(266): error: identifier "saturate" is undefined
   float t = saturate(fac);
             ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_math_util.h(96): error: identifier "saturate" is undefined
    Fac = saturate(Fac1);
          ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_gradient.h(72): error: identifier "saturate" is undefined
   f = saturate(f);
       ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_closure.h(130): error: identifier "saturate" is undefined
     float diffuse_weight = (1.0f - saturate(metallic)) * (1.0f - saturate(transmission));
                                    ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_closure.h(687): error: identifier "saturate" is undefined
      bsdf->sigma = saturate(param1);
                    ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_closure.h(981): error: identifier "saturate" is undefined
   weight = saturate(weight);
            ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_image.h(248): error: identifier "saturate" is undefined
     weight.x = saturate((weight.x - 0.5f*(1.0f - blend))/blend);
                ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_image.h(253): error: identifier "saturate" is undefined
     weight.y = saturate((weight.y - 0.5f*(1.0f - blend))/blend);
                ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_image.h(258): error: identifier "saturate" is undefined
     weight.x = saturate((weight.x - 0.5f*(1.0f - blend))/blend);
                ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_ramp.h(46): error: identifier "saturate" is undefined
   f = saturate(f)*(table_size-1);
       ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_musgrave.h(171): error: identifier "saturate" is undefined
    weight = saturate(signal * gain);
             ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/svm/svm_brick.h(50): error: identifier "saturate" is undefined
   float tint = saturate((brick_noise((rownum << 16) + (bricknum & 0xFFFF)) + bias));
                ^

/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernel_passes.h(265): error: identifier "saturate" is undefined
    float mist = saturate((depth - mist_start)*mist_inv_depth);
                 ^

53 errors detected in the compilation of "/home/daimia/blender-2.79a-linux-glibc219-x86_64/2.79/scripts/addons/cycles/source/kernel/kernels/cuda/kernel.cu".
CUDA kernel compilation failed, see console for details.

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/dev/render/cycles/gpu_rendering.html
```

**Comment by monajalal** [comment]
> You might find my conda environment definition useful, everything seems to execute for me. see attached. [environment.zip](https://github.com/zju3dv/pvnet-rendering/files/3756617/environment.zip)

@sherwoac 

when I used your version of openexr, I get this error. Any chance you could help me?

```
root@fae597dbdb79:/home/pvnet-rendering# /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/pip3 install openexr==1.3.2       
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.
Collecting openexr==1.3.2
  Using cached OpenEXR-1.3.2.tar.gz (10 kB)
Building wheels for collected packages: openexr
  Building wheel for openexr (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/python3.5m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4zlf4z16
       cwd: /tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying Imath.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building 'OpenEXR' extension
  creating build/temp.linux-x86_64-3.5
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/OpenEXR -I/home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m -c OpenEXR.cpp -o build/temp.linux-x86_64-3.5/OpenEXR.o -g -DVERSION="1.3.2"
  cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
  OpenEXR.cpp:1:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for openexr
  Running setup.py clean for openexr
Failed to build openexr
Installing collected packages: openexr
    Running setup.py install for openexr ... error
    ERROR: Command errored out with exit status 1:
     command: /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/python3.5m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ii1fw_qf/install-record.txt --single-version-externally-managed --compile --install-headers /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m/openexr
         cwd: /tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying Imath.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building 'OpenEXR' extension
    creating build/temp.linux-x86_64-3.5
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include/OpenEXR -I/usr/local/include/OpenEXR -I/opt/local/include/OpenEXR -I/home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m -c OpenEXR.cpp -o build/temp.linux-x86_64-3.5/OpenEXR.o -g -DVERSION="1.3.2"
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    OpenEXR.cpp:1:10: fatal error: Python.h: No such file or directory
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/bin/python3.5m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gn34_jok/openexr_6a37cae39f724a1fbf26698bbf239c09/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ii1fw_qf/install-record.txt --single-version-externally-managed --compile --install-headers /home/blender-2.79a-linux-glibc219-x86_64/2.79/python/include/python3.5m/openexr Check the logs for full command output.

```
