### ISSUE TITLE
Problem in rendering images

### ISSUE THREAD

**Issue by mohammad-h-b** [zju3dv/pvnet-rendering#59]
Hi,
While running `python run.py --type rendering` I get the following error while `python run.py --type fuse` works just fine (blender 2.91).

![14](https://user-images.githubusercontent.com/43095906/107409508-44865080-6ada-11eb-8971-01c835ee49fe.png)

With blender 2.79a, I get this error message when trying to install transforms3d:

![15](https://user-images.githubusercontent.com/43095906/107437584-35fd6080-6afd-11eb-896e-2bc218f82036.png)

**Comment by pengsida** [comment]
Use blender 2.79a.
Install transform3d according to https://github.com/zju3dv/pvnet-rendering/issues/3

**Comment by mohammad-h-b** [comment]
Thanks. When running [this](https://github.com/pengsida/configuration/blob/master/blender/install_pip.py), I get this error:

Traceback (most recent call last):
  File "/home/mohammad/Downloads/get-pip.py", line 24244, in <module>
    main()
  File "/home/mohammad/Downloads/get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "/home/mohammad/Downloads/get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/tmp/tmphw2jgbgm/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

**Comment by pengsida** [comment]
Use python3.

**Comment by mohammad-h-b** [comment]
Yes, I'm uisng python3 as the file in `cd /path-to-blender/2.79/python/bin` is `python3.5m`.

**Comment by pengsida** [comment]
It is not a problem of this code.
Please google it.
