### ISSUE TITLE
NVCC sm-75 Error: Cuda kernel compilation failed

### ISSUE THREAD

**Issue by MiriamJo** [zju3dv/pvnet-rendering#72]
I am trying to ude the rendering type.
For the cat.ply model it works fantastic and generates all the jpegs, depths and masks.
However, when I try to run the other models, it shows following error:

--------------------------------------------
/opt/blender2.79a/2.79/python/bin/python3.5m run.py --type rendering
found bundled python: /opt/blender2.79a/2.79/python
Read blend: /home/miriam/Projekte/Masterarbeit/pvnet-rendering/data/blank.blend

Successfully imported '/home/miriam/Projekte/Masterarbeit/pvnet-rendering/data/LINEMOD/glue/glue.ply' in 0.518 sec
5.845498 0.000000 0.000000
Fra:1 Mem:16.18M (0.00M, Peak 16.18M) | Time:00:00.05 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Lamp1
Fra:1 Mem:16.18M (0.00M, Peak 16.18M) | Time:00:00.05 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Lamp0
Fra:1 Mem:16.18M (0.00M, Peak 16.18M) | Time:00:00.05 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | glue
Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.07 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Empty
Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.07 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | Camera
Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.07 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Initializing
Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.07 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Loading render kernels (may take a few minutes the first time)
CUDA version 9.10 detected, build may succeed but only CUDA 8.0 is officially supported.
Compiling CUDA kernel ...
"/usr/local/cuda/bin/nvcc" -arch=sm_75 --cubin "/opt/blender2.79a/2.79/scripts/addons/cycles/source/kernel/kernels/cuda/kernel.cu" -o "/home/miriam/.cache/cycles/kernels/cycles_kernel_sm75_65B79480ADC67BEBF4D71E3B0A71C6B2.cubin" -m64 --ptxas-options="-v" --use_fast_math -DNVCC -D__KERNEL_CUDA_VERSION__=90 -I"/opt/blender2.79a/2.79/scripts/addons/cycles/source" 
nvcc fatal   : Value 'sm_75' is not defined for option 'gpu-architecture'
CUDA kernel compilation failed, see console for details.

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/dev/render/cycles/gpu_rendering.html

Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.08 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Error | CUDA kernel compilation failed, see console for details.
Error: CUDA kernel compilation failed, see console for details.
Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.08 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Waiting for render to start
Fra:1 Mem:18.26M (0.00M, Peak 23.18M) | Time:00:00.08 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Cancel | CUDA kernel compilation failed, see console for details.
Fra:1 Mem:16.17M (0.00M, Peak 23.18M) | Time:00:00.11 | Sce: Scene Ve:0 Fa:0 La:0
Error: CUDA kernel compilation failed, see console for details.
Traceback (most recent call last):
  File "/home/miriam/Projekte/Masterarbeit/pvnet-rendering/blender/render_backend.py", line 456, in <module>
    batch_render_with_linemod(args, camera)
  File "/home/miriam/Projekte/Masterarbeit/pvnet-rendering/blender/render_backend.py", line 379, in batch_render_with_linemod
    render(camera, '{}/{}'.format(args.output_dir, i), pose)
  File "/home/miriam/Projekte/Masterarbeit/pvnet-rendering/blender/render_backend.py", line 248, in render
    bpy.ops.render.render(write_still=True)
  File "/opt/blender2.79a/2.79/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: CUDA kernel compilation failed, see console for details.

Blender quit

---------------------------------------
This is the nvidia-smi output (what I'm working with):
NVIDIA-SMI 510.47.03   
Driver Version: 510.47.03    
CUDA Version: 
    current: 9.0
    (up to 11.6 for the driver)
NVIDIA GeForce GTX 1660 Ti (mobile)

I installed Cuda TK 9.0 as another issue told me. However, I cant figure out how to fix the error.
I think [this website](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/) also shows, that my gpu should be compatible with sm-75?

**Comment by MiriamJo** [comment]
I just tried downgrading my pytorch to a version that supports cuda 9.0, it is still not working.

**Comment by MiriamJo** [comment]
**SOLVED**

Against the compiler advise I installed Cuda Toolkit 10 and the fitting CuDNN. I also downgraded gcc and g++ to version 5 (I guess it would also work with 5 and 6). It works like a charm now.
