### ISSUE TITLE
ImportError: No module named 'OpenEXR' after  sudo pip install openexr

### ISSUE THREAD

**Issue by monajalal** [zju3dv/pvnet-rendering#84]
Despite install openexr pip package, it cannot be imported. Could you please suggest a fix?

```
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ sudo pip install openexr
Collecting openexr
  Using cached OpenEXR-1.3.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
Installing collected packages: openexr
Successfully installed openexr-1.3.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(pvrendering) (base) mona@mona-ThinkStation-P7:~/pvnet-rendering$ python run.py --type rendering
Traceback (most recent call last):
  File "run.py", line 24, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 11, in run_rendering
    from blender.render_utils import Renderer, YCBRenderer
  File "/home/mona/pvnet-rendering/blender/render_utils.py", line 9, in <module>
    import OpenEXR
ImportError: No module named 'OpenEXR'

```

https://github.com/zju3dv/pvnet-rendering/issues/84

**Comment by mmkolbe** [comment]
On PVnet environment I'm using Python 3.7 and had no issue installing with `pip install openexr`.

By the way, Mona, have you got the pvnet running on your custom dataset?
